// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

// @formatter:off

#![allow(dead_code)]

use wasmlib::*;

use crate::*;

pub const IDX_PARAM_NUMBER:               usize = 0;
pub const IDX_PARAM_PLAY_PERIOD:          usize = 1;
pub const IDX_RESULT_LAST_WINNING_NUMBER: usize = 2;
pub const IDX_RESULT_ROUND_NUMBER:        usize = 3;
pub const IDX_RESULT_ROUND_STATUS:        usize = 4;
pub const IDX_STATE_BETS:                 usize = 5;
pub const IDX_STATE_LAST_WINNING_NUMBER:  usize = 6;
pub const IDX_STATE_PLAY_PERIOD:          usize = 7;
pub const IDX_STATE_ROUND_NUMBER:         usize = 8;
pub const IDX_STATE_ROUND_STATUS:         usize = 9;

pub const KEY_MAP_LEN: usize = 10;

pub const KEY_MAP: [&str; KEY_MAP_LEN] = [
    PARAM_NUMBER,
    PARAM_PLAY_PERIOD,
    RESULT_LAST_WINNING_NUMBER,
    RESULT_ROUND_NUMBER,
    RESULT_ROUND_STATUS,
    STATE_BETS,
    STATE_LAST_WINNING_NUMBER,
    STATE_PLAY_PERIOD,
    STATE_ROUND_NUMBER,
    STATE_ROUND_STATUS,
];

pub static mut IDX_MAP: [Key32; KEY_MAP_LEN] = [Key32(0); KEY_MAP_LEN];

pub fn idx_map(idx: usize) -> Key32 {
    unsafe {
        IDX_MAP[idx]
    }
}

// @formatter:on
