#!/bin/bash -l

# use: stardust-test [arguments for `go test`]
#
# example: stardust-test -failfast

PATHS=(\
    "packages/transaction/" \
    "packages/vm/core/accounts/..." \
    "packages/vm/core/testcore_stardust/..." \
    "packages/vm/core/evm/..." \
    "packages/vm/vmcontext/..." \
    "packages/peering/..." \
    "packages/chain/chainimpl/" \
    "packages/chain/nodeconnchain/" \
    "packages/chain/messages/" \
    "packages/chain/mempool/" \
    "packages/chain/statemgr/" \
    "packages/chain/consensus/" \
    "packages/metrics/nodeconnmetrics/" \
    "packages/utxodb/" \
    "packages/evm/jsonrpc/jsonrpctest" \
    "packages/dashboard" \
    "packages/nodeconn" \
    "packages/tcrypto/..." \
    "packages/dkg/..." \
    "packages/iscp" \
    "packages/webapi/..." \
    "packages/util/..." \
    "packages/testutil/privtangle" \
)
WD=$PWD

for ((i=0; i<${#PATHS[@]}; i++))
do
    go test "${WD}/${PATHS[i]}" $* || { echo "Tests in ${PATHS[i]} failed" ; exit 1; }
done

echo "All tests passed"
