#!/bin/bash -l

# use: stardust-test [arguments for `go test`]
#
# example: stardust-test -failfast

PATHS=(\
    "packages/transaction/" \
    "packages/vm/core/accounts/..." \
    "packages/vm/core/testcore_stardust/..." \
    "packages/vm/core/evm/..." \
    "packages/vm/vmcontext/..." \
    "packages/peering/..." \
    "packages/chain/chainimpl/" \
    "packages/chain/mempool/" \
    "packages/chain/statemgr/" \
    "packages/chain/consensus/" \
    "packages/utxodb/" \
    "packages/evm/jsonrpc/jsonrpctest" \
    "packages/nodeconn" \
    "packages/testutil/privtangle" \
)
WD=$PWD

for ((i=0; i<${#PATHS[@]}; i++))
do
    go test "${WD}/${PATHS[i]}" $* || { echo "Tests in ${PATHS[i]} failed" ; exit 1; }
done

echo "All tests passed"
