name: timestamp
description: Extremely simple timestamp server
structs: {}
typedefs: {}
state:
funcs:
  now:
views:
  getTimestamp:
    results:
      timestamp: Uint64 // last official timestamp generated
