version: "3.9"

services:
  iota-tools:
    image: iotaledger/iota-tools:devnet
    container_name: iota-tools
    command:
      [
        "iota",
        "start",
        "--force-regenesis",
        "--epoch-duration-ms=60000",
        "--with-faucet",
        "--faucet-amount=1000000000000"
      ]
    ports:
      - "9000:9000"
      - "9123:9123"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "-H", "Content-Type: application/json", "-d", '{"jsonrpc":"2.0","id":1,"method":"iota_getLatestCheckpointSequenceNumber","params":[]}', "http://localhost:9000"]
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 10s
    tmpfs:
      - /tmp
    networks:
      - testnetwork

  evmemulator:
    build:
      context: ../../../
      dockerfile: tools/evm/evmemulator/Dockerfile
    container_name: evmemulator
    ports:
      - "8545:8545"
    depends_on:
      iota-tools:
        condition: service_healthy
    volumes:
      - ./genesis.json:/etc/genesis.json:ro
    command:
      [
        "--node-launch-mode=docker-compose",
        "--genesis=/etc/genesis.json"
      ]
    networks:
      - testnetwork

networks:
  testnetwork:
    driver: bridge
