version: "3.9"

services:
  iota-tools:
    image: iotaledger/iota-tools:devnet
    container_name: iota-tools
    platform: linux/arm64
    command:
      [
        "iota",
        "start",
        "--force-regenesis",
        "--epoch-duration-ms=60000",
        "--with-faucet",
        "--faucet-amount=1000000000000"
      ]
    ports:
      - "9000:9000"
      - "9123:9123"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "-H", "Content-Type: application/json", "-d", '{"jsonrpc":"2.0","id":1,"method":"iota_getLatestCheckpointSequenceNumber","params":[]}', "http://localhost:9000"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    tmpfs:
      - /tmp
    networks:
      - appnet

  evmemulator:
    build:
      context: ../../../
      dockerfile: tools/evm/evmemulator/Dockerfile
    container_name: evmemulator
    ports:
      - "8545:8545"
    depends_on:
      iota-tools:
        condition: service_healthy
    command:
      [
        "--node-launch-mode=docker-compose"
      ]
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"  # Expose NGINX to the host on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - evmemulator
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
