// Code generated by schema tool; DO NOT EDIT.

// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

package coregovernance

import (
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"
)

type CoreGovernanceEvents struct{}

func (e CoreGovernanceEvents) Rotate(
	newAddr wasmtypes.ScAddress,
	oldAddr wasmtypes.ScAddress,
) {
	enc := wasmlib.NewEventEncoder("coregovernance.rotate")
	wasmtypes.AddressEncode(enc, newAddr)
	wasmtypes.AddressEncode(enc, oldAddr)
	wasmlib.EventEmit(enc)
}
