// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package erc20

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

type MapAgentIDToImmutableAllowancesForAgent struct {
	objID int32
}

func (m MapAgentIDToImmutableAllowancesForAgent) GetAllowancesForAgent(key wasmlib.ScAgentID) ImmutableAllowancesForAgent {
	subID := wasmlib.GetObjectID(m.objID, key.KeyID(), wasmlib.TYPE_MAP)
	return ImmutableAllowancesForAgent{objID: subID}
}

type ImmutableErc20State struct {
	id int32
}

func (s ImmutableErc20State) AllAllowances() MapAgentIDToImmutableAllowancesForAgent {
	mapID := wasmlib.GetObjectID(s.id, idxMap[IdxStateAllAllowances], wasmlib.TYPE_MAP)
	return MapAgentIDToImmutableAllowancesForAgent{objID: mapID}
}

func (s ImmutableErc20State) Balances() MapAgentIDToImmutableInt64 {
	mapID := wasmlib.GetObjectID(s.id, idxMap[IdxStateBalances], wasmlib.TYPE_MAP)
	return MapAgentIDToImmutableInt64{objID: mapID}
}

func (s ImmutableErc20State) Supply() wasmlib.ScImmutableInt64 {
	return wasmlib.NewScImmutableInt64(s.id, idxMap[IdxStateSupply])
}

type MapAgentIDToMutableAllowancesForAgent struct {
	objID int32
}

func (m MapAgentIDToMutableAllowancesForAgent) Clear() {
	wasmlib.Clear(m.objID)
}

func (m MapAgentIDToMutableAllowancesForAgent) GetAllowancesForAgent(key wasmlib.ScAgentID) MutableAllowancesForAgent {
	subID := wasmlib.GetObjectID(m.objID, key.KeyID(), wasmlib.TYPE_MAP)
	return MutableAllowancesForAgent{objID: subID}
}

type MutableErc20State struct {
	id int32
}

func (s MutableErc20State) AllAllowances() MapAgentIDToMutableAllowancesForAgent {
	mapID := wasmlib.GetObjectID(s.id, idxMap[IdxStateAllAllowances], wasmlib.TYPE_MAP)
	return MapAgentIDToMutableAllowancesForAgent{objID: mapID}
}

func (s MutableErc20State) Balances() MapAgentIDToMutableInt64 {
	mapID := wasmlib.GetObjectID(s.id, idxMap[IdxStateBalances], wasmlib.TYPE_MAP)
	return MapAgentIDToMutableInt64{objID: mapID}
}

func (s MutableErc20State) Supply() wasmlib.ScMutableInt64 {
	return wasmlib.NewScMutableInt64(s.id, idxMap[IdxStateSupply])
}
