// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmclient from "wasmclient"
import * as app from "./testwasmlib"

export const eventHandlers: wasmclient.EventHandlers = {
	"testwasmlib.test": onTestWasmLibTestThunk,
};

export class EventTest extends wasmclient.Event {
  	public address: wasmclient.Address;
  	public name: wasmclient.String;
}

function onTestWasmLibTestThunk(message: string[]) {
	let e = new EventTest(message);
	e.address = e.nextAddress();
	e.name = e.nextString();
	app.onTestWasmLibTest(e);
}
