[package]
name = "ISC"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Iota = { git = "git@github.com:iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework",  rev ="ae5d5a543a1c2bcb0be2357a7bf5d7f48ccd1a9c" }
MoveStdlib = { git = "git@github.com:iotaledger/iota.git", subdir = "crates/iota-framework/packages/move-stdlib", rev ="ae5d5a543a1c2bcb0be2357a7bf5d7f48ccd1a9c" }
Stardust = { git = "git@github.com:iotaledger/iota.git", subdir = "crates/iota-framework/packages/stardust",  rev ="ae5d5a543a1c2bcb0be2357a7bf5d7f48ccd1a9c"  }

[addresses]
isc = "0x0"
