name: FairRoulette
description: ""
structs:
  Bet:
    amount: Int64
    better: AgentID
    number: Int64
typedefs: {}
state:
  bets: Bet[]
  lastWinningNumber: Int64
  playPeriod: Int32
  roundNumber: Int64
  roundStartedAt: Int32
  roundStatus: Int16
funcs:
  payWinners:
    access: self // only SC itself can invoke this function
  placeBet:
    params:
      number: Int64 // the number a better bets on
  forceReset:
    access: creator // only SC creator can restart the round forcefully 
  playPeriod:
    access: creator // only SC creator can update the play period
    params:
      playPeriod: Int32 // number of minutes in one playing round
views:
  lastWinningNumber:
    results:
      lastWinningNumber: Int64
  roundNumber:
    results:
      roundNumber: Int64
  roundStartedAt:
    results:
      roundStartedAt: Int32
  roundStatus:
    results:
      roundStatus: Int16
