// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";

export const ScName        = "helloworld";
export const ScDescription = "The ubiquitous hello world demo";
export const HScName       = new wasmlib.ScHname(0x0683223c);

export const ResultHelloWorld = "helloWorld";

export const FuncHelloWorld    = "helloWorld";
export const ViewGetHelloWorld = "getHelloWorld";

export const HFuncHelloWorld    = new wasmlib.ScHname(0x9d042e65);
export const HViewGetHelloWorld = new wasmlib.ScHname(0x210439ce);
