// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

export class HelloWorldCall {
	func: wasmlib.ScFunc = new wasmlib.ScFunc(sc.HScName, sc.HFuncHelloWorld);
}

export class HelloWorldContext {
	state: sc.MutableHelloWorldState = new sc.MutableHelloWorldState(wasmlib.ScState.proxy());
}

export class GetHelloWorldCall {
	func: wasmlib.ScView = new wasmlib.ScView(sc.HScName, sc.HViewGetHelloWorld);
	results: sc.ImmutableGetHelloWorldResults = new sc.ImmutableGetHelloWorldResults(wasmlib.ScView.nilProxy);
}

export class GetHelloWorldContext {
	results: sc.MutableGetHelloWorldResults = new sc.MutableGetHelloWorldResults(wasmlib.ScView.nilProxy);
	state: sc.ImmutableHelloWorldState = new sc.ImmutableHelloWorldState(wasmlib.ScState.proxy());
}

export class ScFuncs {
	static helloWorld(_ctx: wasmlib.ScFuncCallContext): HelloWorldCall {
		return new HelloWorldCall();
	}

	static getHelloWorld(_ctx: wasmlib.ScViewCallContext): GetHelloWorldCall {
		const f = new GetHelloWorldCall();
		f.results = new sc.ImmutableGetHelloWorldResults(wasmlib.newCallResultsProxy(f.func));
		return f;
	}
}
