mutation ExecuteTransactionBlock(
	$txBytes: String!
	$signatures: [String!]!
	# @genqlient(pointer: true)
	$showBalanceChanges: Boolean = false
	# @genqlient(pointer: true)
	$showEffects: Boolean = false
	# @genqlient(pointer: true)
	$showRawEffects: Boolean = false
	# @genqlient(pointer: true)
	$showEvents: Boolean = false
	# @genqlient(pointer: true)
	$showInput: Boolean = false
	# @genqlient(pointer: true)
	$showObjectChanges: Boolean = false
	# @genqlient(pointer: true)
	$showRawInput: Boolean = false
) {
	executeTransactionBlock(txBytes: $txBytes, signatures: $signatures) {
		errors
		effects {
			transactionBlock {
				...RPC_TRANSACTION_FIELDS
			}
			objectChanges {
				nodes {
					address
					idCreated
					idDeleted
					inputState {
						version
						digest
						asMoveObject {
							contents {
								type {
									repr
								}
							}
						}
					}
					outputState {
						version
						digest
						owner {
							...RPC_OBJECT_OWNER_FIELDS
						}
						asMoveObject {
							contents {
								type {
									repr
								}
							}
						}
					}
				}
			}
			balanceChanges {
				nodes {
					owner {
						asAddress {
							address
						}
					}
					amount
					coinType {
						repr
					}
				}
			}
		}		
	}
}
