query GetCoins(
	$owner: IotaAddress!,
	# @genqlient(pointer: true)
	$first: Int,
	# @genqlient(pointer: true)
	$cursor: String,
	# @genqlient(pointer: true)
	$fetchCoinType: String = "0x2::iota::IOTA",
) {
	address(address: $owner) {
		address
		coins(first: $first, after: $cursor, type: $fetchCoinType) {
			pageInfo {
				hasNextPage
				endCursor
			}
			nodes {
				coinBalance
				contents {
					type {
						repr
					}
				}
				address
				version
				digest
				previousTransactionBlock {
					digest
				}
			}
		}
	}
}
