query GetDynamicFields(
	$parentId: IotaAddress!,
	# @genqlient(pointer: true)
	$first: Int,
	# @genqlient(pointer: true)
	$cursor: String,
) {
	owner(address: $parentId) {
		dynamicFields(first: $first, after: $cursor) {
			pageInfo {
				...PAGE_INFO
			}
			nodes {
				name {
					bcs
					json
					type {
						layout
						repr
					}
				}
				value {
					__typename
					... on MoveValue {
						json
						type {
							repr
						}
					}
					... on MoveObject {
						contents {
							type {
								repr
							}
							json
						}
						address
						digest
						version
					}
				}
			}
		}
	}
}
