# @genqlient(for: "ObjectFilter.type", pointer: true)
# @genqlient(for: "ObjectFilter.owner", pointer: true)
# @genqlient(for: "ObjectFilter.objectIds", pointer: true)
# @genqlient(for: "ObjectFilter.objectKeys", pointer: true)
query GetOwnedObjects(
	$owner: IotaAddress!
	# @genqlient(pointer: true)
	$limit: Int
	# @genqlient(pointer: true)
	$cursor: String
	# @genqlient(pointer: true)
	$showBcs: Boolean = false
	# @genqlient(pointer: true)
	$showContent: Boolean = false
	# @genqlient(pointer: true)
	$showDisplay: Boolean = false
	# @genqlient(pointer: true)
	$showType: Boolean = false
	# @genqlient(pointer: true)
	$showOwner: Boolean = false
	# @genqlient(pointer: true)
	$showPreviousTransaction: Boolean = false
	# @genqlient(pointer: true)
	$showStorageRebate: Boolean = false
	# @genqlient(pointer: true)
	$filter: ObjectFilter
) {
	address(address: $owner) {
		objects(first: $limit, after: $cursor, filter: $filter) {
			pageInfo {
				...PAGE_INFO
			}
			nodes {
				...RPC_MOVE_OBJECT_FIELDS
			}
		}
	}
}

query GetObject(
	$id: IotaAddress!
	# @genqlient(pointer: true)
	$showBcs: Boolean = false
	# @genqlient(pointer: true)
	$showOwner: Boolean = false
	# @genqlient(pointer: true)
	$showPreviousTransaction: Boolean = false
	# @genqlient(pointer: true)
	$showContent: Boolean = false
	# @genqlient(pointer: true)
	$showDisplay: Boolean = false
	# @genqlient(pointer: true)
	$showType: Boolean = false
	# @genqlient(pointer: true)
	$showStorageRebate: Boolean = false
) {
	object(address: $id) {
		...RPC_OBJECT_FIELDS
	}
}

query TryGetPastObject(
	$id: IotaAddress!
	# @genqlient(pointer: true)
	$version: UInt53
	# @genqlient(pointer: true)
	$showBcs: Boolean = false
	# @genqlient(pointer: true)
	$showOwner: Boolean = false
	# @genqlient(pointer: true)
	$showPreviousTransaction: Boolean = false
	# @genqlient(pointer: true)
	$showContent: Boolean = false
	# @genqlient(pointer: true)
	$showDisplay: Boolean = false
	# @genqlient(pointer: true)
	$showType: Boolean = false
	# @genqlient(pointer: true)
	$showStorageRebate: Boolean = false
) {
	current: object(address: $id) {
		address
		version
	}
	object(address: $id, version: $version) {
		...RPC_OBJECT_FIELDS
	}
}

query MultiGetObjects(
	$ids: [IotaAddress!]!
	# @genqlient(pointer: true)
	$limit: Int
	# @genqlient(pointer: true)
	$cursor: String
	# @genqlient(pointer: true)
	$showBcs: Boolean = false
	# @genqlient(pointer: true)
	$showContent: Boolean = false
	# @genqlient(pointer: true)
	$showDisplay: Boolean = false
	# @genqlient(pointer: true)
	$showType: Boolean = false
	# @genqlient(pointer: true)
	$showOwner: Boolean = false
	# @genqlient(pointer: true)
	$showPreviousTransaction: Boolean = false
	# @genqlient(pointer: true)
	$showStorageRebate: Boolean = false
) {
	objects(first: $limit, after: $cursor, filter: { objectIds: $ids }) {
		pageInfo {
			...PAGE_INFO
		}
		nodes {
			...RPC_OBJECT_FIELDS
		}
	}
}

fragment RPC_OBJECT_FIELDS on Object {
	objectId: address
	version
	status
	asMoveObjectType: asMoveObject @include(if: $showType) {
		contents {
			type {
				repr
			}
		}
	}
	asMoveObjectContent: asMoveObject @include(if: $showContent) {
		contents {
			data
			type {
				repr
				layout
				signature
			}
		}
	}
	asMoveObject @include(if: $showBcs) {
		contents {
			bcs
			type {
				repr
			}
		}
	}
	owner @include(if: $showOwner) {
		...RPC_OBJECT_OWNER_FIELDS
	}
	previousTransactionBlock @include(if: $showPreviousTransaction) {
		digest
	}

	storageRebate @include(if: $showStorageRebate)
	digest
	version
	status
	display @include(if: $showDisplay) {
		key
		value
		error
	}
}

fragment RPC_MOVE_OBJECT_FIELDS on MoveObject {
	objectId: address
	bcs @include(if: $showBcs)
	status
	contents_type: contents @include(if: $showType) {
		type {
			repr
		}
	}

	contents_content: contents @include(if: $showContent) {
		data
		type {
			repr
			layout
			signature
		}
	}

	contents @include(if: $showBcs) {
		bcs
		type {
			repr
		}
	}

	owner @include(if: $showOwner) {
		...RPC_OBJECT_OWNER_FIELDS
	}
	previousTransactionBlock @include(if: $showPreviousTransaction) {
		digest
	}

	storageRebate @include(if: $showStorageRebate)
	digest
	version
	display @include(if: $showDisplay) {
		key
		value
		error
	}
}

fragment RPC_OBJECT_OWNER_FIELDS on ObjectOwner {
	__typename
	... on AddressOwner {
		owner {
			asObject {
				address
			}
			asAddress {
				address
			}
		}
	}
	... on Parent {
		parent {
			address
		}
	}
	... on Shared {
		initialSharedVersion
	}
}
