query QueryEvents(
	$filter: EventFilter!
	# filter missing:
	# - MoveEventField
	# - TimeRange
	# - All, Any, And, Or
	# missing order
	# @genqlient(pointer: true)
	$before: String
	# @genqlient(pointer: true)
	$after: String
	# @genqlient(pointer: true)
	$first: Int
	# @genqlient(pointer: true)
	$last: Int
) {
	events(filter: $filter, first: $first, after: $after, last: $last, before: $before) {
		pageInfo {
			hasNextPage
			hasPreviousPage
			endCursor
			startCursor
		}
		nodes {
			...RPC_EVENTS_FIELDS
		}
	}
}

fragment RPC_EVENTS_FIELDS on Event {
	sendingModule {
		package {
			address
		}
		name
	}
	sender {
		address
	}
	json
	timestamp
}
