name: IncCounter
description: ""
structs: {}
typedefs: {}
state:
  counter: Int64
  numRepeats: Int64
funcs:
  callIncrement: {}
  callIncrementRecurse5x: {}
  endlessLoop: {}
  increment: {}
  incrementWithDelay:
    params:
      delay: Uint32 # delay in seconds
  init:
    params:
      counter: Int64? # value to initialize state counter with
  localStateInternalCall: {}
  localStatePost: {}
  localStateSandboxCall: {}
  postIncrement: {}
  repeatMany:
    params:
      numRepeats: Int64? # number of times to recursively call myself
  testVliCodec: {}
  testVluCodec: {}
  whenMustIncrement:
    params:
      dummy: Int64? # dummy param to prevent 'duplicate outputs not allowed'
views:
  getCounter:
    results:
      counter: Int64
  getVli:
    params:
      ni64: Int64
    results:
      ni64: Int64
      xi64: Int64
      buf: Bytes
      str: String
  getVlu:
    params:
      nu64: Uint64
    results:
      nu64: Uint64
      xu64: Uint64
      buf: Bytes
      str: String
