// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the schema definition file instead

package coreblocklog

import (
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib"
	"github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"
)

type ImmutableGetBlockInfoParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetBlockInfoParams() ImmutableGetBlockInfoParams {
	return ImmutableGetBlockInfoParams{Proxy: wasmlib.NewParamsProxy()}
}

func (s ImmutableGetBlockInfoParams) BlockIndex() wasmtypes.ScImmutableUint32 {
	return wasmtypes.NewScImmutableUint32(s.Proxy.Root(ParamBlockIndex))
}

type MutableGetBlockInfoParams struct {
	Proxy wasmtypes.Proxy
}

func (s MutableGetBlockInfoParams) BlockIndex() wasmtypes.ScMutableUint32 {
	return wasmtypes.NewScMutableUint32(s.Proxy.Root(ParamBlockIndex))
}

type ImmutableGetEventsForBlockParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetEventsForBlockParams() ImmutableGetEventsForBlockParams {
	return ImmutableGetEventsForBlockParams{Proxy: wasmlib.NewParamsProxy()}
}

func (s ImmutableGetEventsForBlockParams) BlockIndex() wasmtypes.ScImmutableUint32 {
	return wasmtypes.NewScImmutableUint32(s.Proxy.Root(ParamBlockIndex))
}

type MutableGetEventsForBlockParams struct {
	Proxy wasmtypes.Proxy
}

func (s MutableGetEventsForBlockParams) BlockIndex() wasmtypes.ScMutableUint32 {
	return wasmtypes.NewScMutableUint32(s.Proxy.Root(ParamBlockIndex))
}

type ImmutableGetEventsForContractParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetEventsForContractParams() ImmutableGetEventsForContractParams {
	return ImmutableGetEventsForContractParams{Proxy: wasmlib.NewParamsProxy()}
}

func (s ImmutableGetEventsForContractParams) ContractHname() wasmtypes.ScImmutableHname {
	return wasmtypes.NewScImmutableHname(s.Proxy.Root(ParamContractHname))
}

func (s ImmutableGetEventsForContractParams) FromBlock() wasmtypes.ScImmutableUint32 {
	return wasmtypes.NewScImmutableUint32(s.Proxy.Root(ParamFromBlock))
}

func (s ImmutableGetEventsForContractParams) ToBlock() wasmtypes.ScImmutableUint32 {
	return wasmtypes.NewScImmutableUint32(s.Proxy.Root(ParamToBlock))
}

type MutableGetEventsForContractParams struct {
	Proxy wasmtypes.Proxy
}

func (s MutableGetEventsForContractParams) ContractHname() wasmtypes.ScMutableHname {
	return wasmtypes.NewScMutableHname(s.Proxy.Root(ParamContractHname))
}

func (s MutableGetEventsForContractParams) FromBlock() wasmtypes.ScMutableUint32 {
	return wasmtypes.NewScMutableUint32(s.Proxy.Root(ParamFromBlock))
}

func (s MutableGetEventsForContractParams) ToBlock() wasmtypes.ScMutableUint32 {
	return wasmtypes.NewScMutableUint32(s.Proxy.Root(ParamToBlock))
}

type ImmutableGetEventsForRequestParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetEventsForRequestParams() ImmutableGetEventsForRequestParams {
	return ImmutableGetEventsForRequestParams{Proxy: wasmlib.NewParamsProxy()}
}

func (s ImmutableGetEventsForRequestParams) RequestID() wasmtypes.ScImmutableRequestID {
	return wasmtypes.NewScImmutableRequestID(s.Proxy.Root(ParamRequestID))
}

type MutableGetEventsForRequestParams struct {
	Proxy wasmtypes.Proxy
}

func (s MutableGetEventsForRequestParams) RequestID() wasmtypes.ScMutableRequestID {
	return wasmtypes.NewScMutableRequestID(s.Proxy.Root(ParamRequestID))
}

type ImmutableGetRequestIDsForBlockParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetRequestIDsForBlockParams() ImmutableGetRequestIDsForBlockParams {
	return ImmutableGetRequestIDsForBlockParams{Proxy: wasmlib.NewParamsProxy()}
}

func (s ImmutableGetRequestIDsForBlockParams) BlockIndex() wasmtypes.ScImmutableUint32 {
	return wasmtypes.NewScImmutableUint32(s.Proxy.Root(ParamBlockIndex))
}

type MutableGetRequestIDsForBlockParams struct {
	Proxy wasmtypes.Proxy
}

func (s MutableGetRequestIDsForBlockParams) BlockIndex() wasmtypes.ScMutableUint32 {
	return wasmtypes.NewScMutableUint32(s.Proxy.Root(ParamBlockIndex))
}

type ImmutableGetRequestReceiptParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetRequestReceiptParams() ImmutableGetRequestReceiptParams {
	return ImmutableGetRequestReceiptParams{Proxy: wasmlib.NewParamsProxy()}
}

func (s ImmutableGetRequestReceiptParams) RequestID() wasmtypes.ScImmutableRequestID {
	return wasmtypes.NewScImmutableRequestID(s.Proxy.Root(ParamRequestID))
}

type MutableGetRequestReceiptParams struct {
	Proxy wasmtypes.Proxy
}

func (s MutableGetRequestReceiptParams) RequestID() wasmtypes.ScMutableRequestID {
	return wasmtypes.NewScMutableRequestID(s.Proxy.Root(ParamRequestID))
}

type ImmutableGetRequestReceiptsForBlockParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableGetRequestReceiptsForBlockParams() ImmutableGetRequestReceiptsForBlockParams {
	return ImmutableGetRequestReceiptsForBlockParams{Proxy: wasmlib.NewParamsProxy()}
}

func (s ImmutableGetRequestReceiptsForBlockParams) BlockIndex() wasmtypes.ScImmutableUint32 {
	return wasmtypes.NewScImmutableUint32(s.Proxy.Root(ParamBlockIndex))
}

type MutableGetRequestReceiptsForBlockParams struct {
	Proxy wasmtypes.Proxy
}

func (s MutableGetRequestReceiptsForBlockParams) BlockIndex() wasmtypes.ScMutableUint32 {
	return wasmtypes.NewScMutableUint32(s.Proxy.Root(ParamBlockIndex))
}

type ImmutableIsRequestProcessedParams struct {
	Proxy wasmtypes.Proxy
}

func NewImmutableIsRequestProcessedParams() ImmutableIsRequestProcessedParams {
	return ImmutableIsRequestProcessedParams{Proxy: wasmlib.NewParamsProxy()}
}

func (s ImmutableIsRequestProcessedParams) RequestID() wasmtypes.ScImmutableRequestID {
	return wasmtypes.NewScImmutableRequestID(s.Proxy.Root(ParamRequestID))
}

type MutableIsRequestProcessedParams struct {
	Proxy wasmtypes.Proxy
}

func (s MutableIsRequestProcessedParams) RequestID() wasmtypes.ScMutableRequestID {
	return wasmtypes.NewScMutableRequestID(s.Proxy.Root(ParamRequestID))
}
