/*
Wasp API

REST API for the Wasp node

API version: 0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IotaObject type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IotaObject{}

// IotaObject struct for IotaObject
type IotaObject struct {
	Id []int32 `json:"id"`
	Type ObjectType `json:"type"`
}

type _IotaObject IotaObject

// NewIotaObject instantiates a new IotaObject object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIotaObject(id []int32, type_ ObjectType) *IotaObject {
	this := IotaObject{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewIotaObjectWithDefaults instantiates a new IotaObject object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIotaObjectWithDefaults() *IotaObject {
	this := IotaObject{}
	return &this
}

// GetId returns the Id field value
func (o *IotaObject) GetId() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *IotaObject) GetIdOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id, true
}

// SetId sets field value
func (o *IotaObject) SetId(v []int32) {
	o.Id = v
}

// GetType returns the Type field value
func (o *IotaObject) GetType() ObjectType {
	if o == nil {
		var ret ObjectType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *IotaObject) GetTypeOk() (*ObjectType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *IotaObject) SetType(v ObjectType) {
	o.Type = v
}

func (o IotaObject) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IotaObject) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *IotaObject) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIotaObject := _IotaObject{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIotaObject)

	if err != nil {
		return err
	}

	*o = IotaObject(varIotaObject)

	return err
}

type NullableIotaObject struct {
	value *IotaObject
	isSet bool
}

func (v NullableIotaObject) Get() *IotaObject {
	return v.value
}

func (v *NullableIotaObject) Set(val *IotaObject) {
	v.value = val
	v.isSet = true
}

func (v NullableIotaObject) IsSet() bool {
	return v.isSet
}

func (v *NullableIotaObject) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIotaObject(val *IotaObject) *NullableIotaObject {
	return &NullableIotaObject{value: val, isSet: true}
}

func (v NullableIotaObject) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIotaObject) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


