/*
Wasp API

REST API for the Wasp node

API version: 0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the AccountFoundriesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountFoundriesResponse{}

// AccountFoundriesResponse struct for AccountFoundriesResponse
type AccountFoundriesResponse struct {
	FoundrySerialNumbers []int32 `json:"foundrySerialNumbers"`
}

// NewAccountFoundriesResponse instantiates a new AccountFoundriesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountFoundriesResponse(foundrySerialNumbers []int32) *AccountFoundriesResponse {
	this := AccountFoundriesResponse{}
	this.FoundrySerialNumbers = foundrySerialNumbers
	return &this
}

// NewAccountFoundriesResponseWithDefaults instantiates a new AccountFoundriesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountFoundriesResponseWithDefaults() *AccountFoundriesResponse {
	this := AccountFoundriesResponse{}
	return &this
}

// GetFoundrySerialNumbers returns the FoundrySerialNumbers field value
func (o *AccountFoundriesResponse) GetFoundrySerialNumbers() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.FoundrySerialNumbers
}

// GetFoundrySerialNumbersOk returns a tuple with the FoundrySerialNumbers field value
// and a boolean to check if the value has been set.
func (o *AccountFoundriesResponse) GetFoundrySerialNumbersOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FoundrySerialNumbers, true
}

// SetFoundrySerialNumbers sets field value
func (o *AccountFoundriesResponse) SetFoundrySerialNumbers(v []int32) {
	o.FoundrySerialNumbers = v
}

func (o AccountFoundriesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountFoundriesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["foundrySerialNumbers"] = o.FoundrySerialNumbers
	return toSerialize, nil
}

type NullableAccountFoundriesResponse struct {
	value *AccountFoundriesResponse
	isSet bool
}

func (v NullableAccountFoundriesResponse) Get() *AccountFoundriesResponse {
	return v.value
}

func (v *NullableAccountFoundriesResponse) Set(val *AccountFoundriesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountFoundriesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountFoundriesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountFoundriesResponse(val *AccountFoundriesResponse) *NullableAccountFoundriesResponse {
	return &NullableAccountFoundriesResponse{value: val, isSet: true}
}

func (v NullableAccountFoundriesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountFoundriesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


