/*
Wasp API

REST API for the Wasp node

API version: 0.4.0-alpha.8-16-g83edf92b9
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
)

// checks if the CallTarget type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CallTarget{}

// CallTarget struct for CallTarget
type CallTarget struct {
	Contract uint32 `json:"contract"`
	EntryPoint uint32 `json:"entryPoint"`
}

// NewCallTarget instantiates a new CallTarget object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCallTarget(contract uint32, entryPoint uint32) *CallTarget {
	this := CallTarget{}
	this.Contract = contract
	this.EntryPoint = entryPoint
	return &this
}

// NewCallTargetWithDefaults instantiates a new CallTarget object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCallTargetWithDefaults() *CallTarget {
	this := CallTarget{}
	return &this
}

// GetContract returns the Contract field value
func (o *CallTarget) GetContract() uint32 {
	if o == nil {
		var ret uint32
		return ret
	}

	return o.Contract
}

// GetContractOk returns a tuple with the Contract field value
// and a boolean to check if the value has been set.
func (o *CallTarget) GetContractOk() (*uint32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Contract, true
}

// SetContract sets field value
func (o *CallTarget) SetContract(v uint32) {
	o.Contract = v
}

// GetEntryPoint returns the EntryPoint field value
func (o *CallTarget) GetEntryPoint() uint32 {
	if o == nil {
		var ret uint32
		return ret
	}

	return o.EntryPoint
}

// GetEntryPointOk returns a tuple with the EntryPoint field value
// and a boolean to check if the value has been set.
func (o *CallTarget) GetEntryPointOk() (*uint32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntryPoint, true
}

// SetEntryPoint sets field value
func (o *CallTarget) SetEntryPoint(v uint32) {
	o.EntryPoint = v
}

func (o CallTarget) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CallTarget) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["contract"] = o.Contract
	toSerialize["entryPoint"] = o.EntryPoint
	return toSerialize, nil
}

type NullableCallTarget struct {
	value *CallTarget
	isSet bool
}

func (v NullableCallTarget) Get() *CallTarget {
	return v.value
}

func (v *NullableCallTarget) Set(val *CallTarget) {
	v.value = val
	v.isSet = true
}

func (v NullableCallTarget) IsSet() bool {
	return v.isSet
}

func (v *NullableCallTarget) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCallTarget(val *CallTarget) *NullableCallTarget {
	return &NullableCallTarget{value: val, isSet: true}
}

func (v NullableCallTarget) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCallTarget) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


