// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmtypes from "wasmlib/wasmtypes";
import * as sc from "./index";

export class ArrayOfImmutableDonation extends wasmtypes.ScProxy {

	length(): u32 {
		return this.proxy.length();
	}

	getDonation(index: u32): sc.ImmutableDonation {
		return new sc.ImmutableDonation(this.proxy.index(index));
	}
}

export class ImmutableDonateWithFeedbackState extends wasmtypes.ScProxy {
	log(): sc.ArrayOfImmutableDonation {
		return new sc.ArrayOfImmutableDonation(this.proxy.root(sc.StateLog));
	}

	maxDonation(): wasmtypes.ScImmutableUint64 {
		return new wasmtypes.ScImmutableUint64(this.proxy.root(sc.StateMaxDonation));
	}

	totalDonation(): wasmtypes.ScImmutableUint64 {
		return new wasmtypes.ScImmutableUint64(this.proxy.root(sc.StateTotalDonation));
	}
}

export class ArrayOfMutableDonation extends wasmtypes.ScProxy {

	appendDonation(): sc.MutableDonation {
		return new sc.MutableDonation(this.proxy.append());
	}

	clear(): void {
		this.proxy.clearArray();
	}

	length(): u32 {
		return this.proxy.length();
	}

	getDonation(index: u32): sc.MutableDonation {
		return new sc.MutableDonation(this.proxy.index(index));
	}
}

export class MutableDonateWithFeedbackState extends wasmtypes.ScProxy {
	asImmutable(): sc.ImmutableDonateWithFeedbackState {
		return new sc.ImmutableDonateWithFeedbackState(this.proxy);
	}

	log(): sc.ArrayOfMutableDonation {
		return new sc.ArrayOfMutableDonation(this.proxy.root(sc.StateLog));
	}

	maxDonation(): wasmtypes.ScMutableUint64 {
		return new wasmtypes.ScMutableUint64(this.proxy.root(sc.StateMaxDonation));
	}

	totalDonation(): wasmtypes.ScMutableUint64 {
		return new wasmtypes.ScMutableUint64(this.proxy.root(sc.StateTotalDonation));
	}
}
