package iotagraphql

import (
	"github.com/iotaledger/wasp/v2/clients/iotagraphql/graphqltypes"
)

// Note: Request types (Get*, Query*, etc.) are now defined directly in this package in requests.go
// WaitParams, RetryCondition, and gas constants are defined in helpers.go

// Re-export iotajsonrpc types as part of the public API.
// These types are used by the IotaClient interface and are the common data model
// across different client implementations (GraphQL, JSON-RPC, etc.).
type (
	IotaTransactionBlockResponseOptions   = graphqltypes.IotaTransactionBlockResponseOptions
	IotaTransactionBlockResponseQuery     = graphqltypes.IotaTransactionBlockResponseQuery
	IotaTransactionBlockResponse          = graphqltypes.IotaTransactionBlockResponse
	IotaObjectDataOptions                 = graphqltypes.IotaObjectDataOptions
	IotaObjectResponseQuery               = graphqltypes.IotaObjectResponseQuery
	IotaObjectDataFilter                  = graphqltypes.IotaObjectDataFilter
	IotaObjectResponse                    = graphqltypes.IotaObjectResponse
	IotaPastObjectResponse                = graphqltypes.IotaPastObjectResponse
	IotaSystemStateSummary                = graphqltypes.IotaSystemStateSummary
	IotaCoinMetadata                      = graphqltypes.IotaCoinMetadata
	BigInt                                = graphqltypes.BigInt
	CoinType                              = graphqltypes.CoinType
	Coins                                 = graphqltypes.Coins
	CoinPage                              = graphqltypes.CoinPage
	Balance                               = graphqltypes.Balance
	Supply                                = graphqltypes.Supply
	DevInspectResults                     = graphqltypes.DevInspectResults
	DynamicFieldPage                      = graphqltypes.DynamicFieldPage
	ObjectsPage                           = graphqltypes.ObjectsPage
	TransactionBlocksPage                 = graphqltypes.TransactionBlocksPage
	TransactionBytes                      = graphqltypes.TransactionBytes
	EventPage                             = graphqltypes.EventPage
	IotaNamePage                          = graphqltypes.IotaNamePage
	Checkpoint                            = graphqltypes.Checkpoint
	CheckpointPage                        = graphqltypes.CheckpointPage
	ProtocolConfig                        = graphqltypes.ProtocolConfig
	IotaParsedData                        = graphqltypes.IotaParsedData
	IotaParsedMoveObject                  = graphqltypes.IotaParsedMoveObject
	IotaRawData                           = graphqltypes.IotaRawData
	IotaRawMoveObject                     = graphqltypes.IotaRawMoveObject
	ObjectOwner                           = graphqltypes.ObjectOwner
	ObjectOwnerInternal                   = graphqltypes.ObjectOwnerInternal
	IotaTransactionBlockEffectsV1         = graphqltypes.IotaTransactionBlockEffectsV1
	ExecutionResultType                   = graphqltypes.ExecutionResultType
	MutableReferenceOutputType            = graphqltypes.MutableReferenceOutputType
	ReturnValueType                       = graphqltypes.ReturnValueType
	EventID                               = graphqltypes.EventID
	CoinValue                             = graphqltypes.CoinValue
	ProgrammableTransactionBlockPureInput = graphqltypes.ProgrammableTransactionBlockPureInput
	IotaTransactionBlockData              = graphqltypes.IotaTransactionBlockData
	IotaTransactionBlockEffects           = graphqltypes.IotaTransactionBlockEffects
	IotaEvent                             = graphqltypes.IotaEvent
	ObjectChange                          = graphqltypes.JSONRPCObjectChange
	BalanceChange                         = graphqltypes.BalanceChange
	IotaObjectData                        = graphqltypes.IotaObjectData
	Coin                                  = graphqltypes.Coin
	TransactionFilter                     = graphqltypes.TransactionFilter
	// IotaEventFilter is an alias for graphqltypes.EventFilter.
	// Note: EventFilter is generated by genqlient and differs from graphqltypes.EventFilter.
	// Re-exported with "Iota" prefix to avoid naming conflicts.
	IotaEventFilter               = graphqltypes.EventFilter
	IotaAndOrEventFilter          = graphqltypes.AndOrEventFilter
	IotaEventFilterMoveEventField = graphqltypes.EventFilterMoveEventField
	// DryRunResult is an alias for graphqltypes.DryRunTransactionBlockResponse.
	// Note: DryRunTransactionBlockResponse from generated.go is different from iotajsonrpc.
	DryRunResult            = graphqltypes.DryRunTransactionBlockResponse
	GasCostSummary          = graphqltypes.GasCostSummary
	PickedCoins             = graphqltypes.PickedCoins
	DynamicFieldInfo        = graphqltypes.DynamicFieldInfo
	IotaObjectResponseError = graphqltypes.IotaObjectResponseError
	IotaPastObject          = graphqltypes.IotaPastObject
	VersionTooHigh          = graphqltypes.VersionTooHigh
	VersionNotFoundData     = graphqltypes.VersionNotFoundData
	OwnedObjectRef          = graphqltypes.OwnedObjectRef
	IotaObjectRef           = graphqltypes.IotaObjectRef
)

// Re-export iotajsonrpc coin picking method constants
const (
	PickMethodSmaller = graphqltypes.PickMethodSmaller
	PickMethodBigger  = graphqltypes.PickMethodBigger
	PickMethodByOrder = graphqltypes.PickMethodByOrder
)

// Re-export iotajsonrpc constants
var (
	IotaCoinType = graphqltypes.IotaCoinType
)

// Re-export iotajsonrpc functions
var (
	NewBigInt               = graphqltypes.NewBigInt
	NewBigIntInt64          = graphqltypes.NewBigIntInt64
	PickupCoins             = graphqltypes.PickupCoins
	PickupCoinsWithFilter   = graphqltypes.PickupCoinsWithFilter
	PickupCoinWithFilter    = graphqltypes.PickupCoinWithFilter
	PickupCoinsWithCointype = graphqltypes.PickupCoinsWithCointype
	MustCoinTypeFromString  = graphqltypes.MustCoinTypeFromString
	CoinTypeFromString      = graphqltypes.CoinTypeFromString
)
