// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package tokenregistry

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib/wasmtypes"

type Token struct {
	Created     uint64              // creation timestamp
	Description string              // description what minted token represents
	MintedBy    wasmtypes.ScAgentID // original minter
	Owner       wasmtypes.ScAgentID // current owner
	Supply      uint64              // amount of tokens originally minted
	Updated     uint64              // last update timestamp
	UserDefined string              // any user defined text
}

func NewTokenFromBytes(buf []byte) *Token {
	dec := wasmtypes.NewWasmDecoder(buf)
	data := &Token{}
	data.Created = wasmtypes.DecodeUint64(dec)
	data.Description = wasmtypes.DecodeString(dec)
	data.MintedBy = wasmtypes.DecodeAgentID(dec)
	data.Owner = wasmtypes.DecodeAgentID(dec)
	data.Supply = wasmtypes.DecodeUint64(dec)
	data.Updated = wasmtypes.DecodeUint64(dec)
	data.UserDefined = wasmtypes.DecodeString(dec)
	dec.Close()
	return data
}

func (o *Token) Bytes() []byte {
	enc := wasmtypes.NewWasmEncoder()
	wasmtypes.EncodeUint64(enc, o.Created)
	wasmtypes.EncodeString(enc, o.Description)
	wasmtypes.EncodeAgentID(enc, o.MintedBy)
	wasmtypes.EncodeAgentID(enc, o.Owner)
	wasmtypes.EncodeUint64(enc, o.Supply)
	wasmtypes.EncodeUint64(enc, o.Updated)
	wasmtypes.EncodeString(enc, o.UserDefined)
	return enc.Buf()
}

type ImmutableToken struct {
	proxy wasmtypes.Proxy
}

func (o ImmutableToken) Exists() bool {
	return o.proxy.Exists()
}

func (o ImmutableToken) Value() *Token {
	return NewTokenFromBytes(o.proxy.Get())
}

type MutableToken struct {
	proxy wasmtypes.Proxy
}

func (o MutableToken) Delete() {
	o.proxy.Delete()
}

func (o MutableToken) Exists() bool {
	return o.proxy.Exists()
}

func (o MutableToken) SetValue(value *Token) {
	o.proxy.Set(value.Bytes())
}

func (o MutableToken) Value() *Token {
	return NewTokenFromBytes(o.proxy.Get())
}
