name: TestWasmLib
description: Exercise all aspects of WasmLib
structs: {}
typedefs:
  StringArray: String[]
state:
  arrays: map[String]StringArray
funcs:
  arrayClear:
    params:
      name: String
  arrayCreate:
    params:
      name: String
  arraySet:
    params:
      index: Int32
      name: String
      value: String
  paramTypes:
    params:
      address: Address?
      agentID: AgentID?
      bytes: Bytes?
      chainID: ChainID?
      color: Color?
      hash: Hash?
      hname: Hname?
      int16: Int16?
      int32: Int32?
      int64: Int64?
      param=@: Bytes? // special hook to be able to pass key/values as raw bytes
      requestID: RequestID?
      string: String?
views:
  arrayLength:
    params:
      name: String
    results:
      length: Int32
  arrayValue:
    params:
      index: Int32
      name: String
    results:
      value: String
  blockRecord:
    params:
      blockIndex: Int32
      recordIndex: Int32
    results:
      record: Bytes
  blockRecords:
    params:
      blockIndex: Int32
    results:
      count: Int32
  iotaBalance:
    results:
      iotas: Int64
