// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package executiontime

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

type ImmutableexecutiontimeState struct {
	proxy wasmtypes.Proxy
}

// current owner of this smart contract
func (s ImmutableexecutiontimeState) Owner() wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(s.proxy.Root(StateOwner))
}

type MutableexecutiontimeState struct {
	proxy wasmtypes.Proxy
}

func (s MutableexecutiontimeState) AsImmutable() ImmutableexecutiontimeState {
	return ImmutableexecutiontimeState(s)
}

// current owner of this smart contract
func (s MutableexecutiontimeState) Owner() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(s.proxy.Root(StateOwner))
}
