name: CoreAccounts
description: Chain account ledger contract
structs: {}
typedefs: {}
state: {}
funcs:
  deposit: {}
  transferAllowanceTo:
    params:
      agentID=a: AgentID
      forceOpenAccount=c: Bool?
  withdraw: {}
  harvest: 
    params:
      forceMinimumIotas=f: Uint64
  foundryCreateNew:
    params:
      tokenScheme=t: Bytes
      tokenTag=g: Bytes
    results:
      foundrySN=s: Uint32
  foundryDestroy:
    params:
      foundrySN=s: Uint32
  foundryModifySupply:
    params:
      foundrySN=s: Uint32
      supplyDeltaAbs=d: BigInt
      destroyTokens=y: Bool

views:
  balance:
    params:
      agentID=a: AgentID
    results:
      balances=this: map[TokenID]Uint64
  totalAssets:
    results:
      assets=this: map[TokenID]Uint64
  accounts:
    results:
      allAccounts=this: map[TokenID]Uint64
  getAccountNonce:
    params:
      foundrySN=s: Uint32
    results:
      accountNonce=n: Uint64
  getNativeTokenIDRegistry:
    results:
      mapping=G: map[TokenID]Bool
  foundryOutput:
    params:
      foundrySN=s: Uint32
    results:
      foundryOutputBin=b: Bytes
  accountNFTs:
    params:
      agentID=a: AgentID
    results:
      nftIDs=i: Bytes
  nftData:
    params:
      nftID=z: Bytes
    results:
      nftData=e: Bytes
