// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

package generator

import "github.com/iotaledger/wasp/tools/schema/model"

var commonTemplates = model.StringMap{
	// *******************************
	"else": `
`,
	// *******************************
	"nil": `
`,
	// *******************************
	"newline": `

`,
	// *******************************
	"copyright": `
$#emit initGlobals
$#if copyrightMessage userCopyrightMessage defaultCopyrightMessage
`,
	// *******************************
	"userCopyrightMessage": `
$copyrightMessage
`,
	// *******************************
	"defaultCopyrightMessage": `
// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

`,
	// *******************************
	"warning": `
// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

`,
	// *******************************
	"test.go": `
$#emit copyright
package test

import (
	"testing"

	"$module/go/$package"
	"github.com/iotaledger/wasp/packages/wasmvm/wasmsolo"
	"github.com/stretchr/testify/require"
)

func TestDeploy(t *testing.T) {
	ctx := wasmsolo.NewSoloContext(t, $package.ScName, $package.OnLoad)
	require.NoError(t, ctx.ContractExists($package.ScName))
}
`,
	// *******************************
	"setupInitFunc": `
$#set initFunc 
$#if init setInitFunc
`,
	// *******************************
	"setInitFunc": `
$#set initFunc Init
`,
}
