// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package testwasmlib

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	ScName        = "testwasmlib"
	ScDescription = "Exercise all aspects of WasmLib"
	HScName       = wasmlib.ScHname(0x89703a45)
)

const (
	ParamAddress     = "address"
	ParamAgentID     = "agentID"
	ParamBlockIndex  = "blockIndex"
	ParamBool        = "bool"
	ParamBytes       = "bytes"
	ParamChainID     = "chainID"
	ParamColor       = "color"
	ParamHash        = "hash"
	ParamHname       = "hname"
	ParamIndex       = "index"
	ParamInt16       = "int16"
	ParamInt32       = "int32"
	ParamInt64       = "int64"
	ParamInt8        = "int8"
	ParamName        = "name"
	ParamParam       = "this"
	ParamRecordIndex = "recordIndex"
	ParamRequestID   = "requestID"
	ParamString      = "string"
	ParamUint16      = "uint16"
	ParamUint32      = "uint32"
	ParamUint64      = "uint64"
	ParamUint8       = "uint8"
	ParamValue       = "value"
)

const (
	ResultCount  = "count"
	ResultIotas  = "iotas"
	ResultLength = "length"
	ResultRandom = "random"
	ResultRecord = "record"
	ResultValue  = "value"
)

const (
	StateArrays = "arrays"
	StateRandom = "random"
)

const (
	FuncArrayClear   = "arrayClear"
	FuncArrayCreate  = "arrayCreate"
	FuncArraySet     = "arraySet"
	FuncParamTypes   = "paramTypes"
	FuncRandom       = "random"
	FuncTriggerEvent = "triggerEvent"
	ViewArrayLength  = "arrayLength"
	ViewArrayValue   = "arrayValue"
	ViewBlockRecord  = "blockRecord"
	ViewBlockRecords = "blockRecords"
	ViewGetRandom    = "getRandom"
	ViewIotaBalance  = "iotaBalance"
)

const (
	HFuncArrayClear   = wasmlib.ScHname(0x88021821)
	HFuncArrayCreate  = wasmlib.ScHname(0x1ed5b23b)
	HFuncArraySet     = wasmlib.ScHname(0x2c4150b3)
	HFuncParamTypes   = wasmlib.ScHname(0x6921c4cd)
	HFuncRandom       = wasmlib.ScHname(0xe86c97ca)
	HFuncTriggerEvent = wasmlib.ScHname(0xd5438ac6)
	HViewArrayLength  = wasmlib.ScHname(0x3a831021)
	HViewArrayValue   = wasmlib.ScHname(0x662dbd81)
	HViewBlockRecord  = wasmlib.ScHname(0xad13b2f8)
	HViewBlockRecords = wasmlib.ScHname(0x16e249ea)
	HViewGetRandom    = wasmlib.ScHname(0x46263045)
	HViewIotaBalance  = wasmlib.ScHname(0x9d3920bd)
)
