name: Clients-IotaGo

on:
  pull_request:
    branches: [ "develop" ]

jobs:

  TestAndBuild:
    runs-on: [self-hosted, Linux, X64, wasp]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache-dependency-path: clients/iota-go/go.sum

    - name: Test
      run: |
        cd clients/iota-go
        go test -v ./...
