name: Clients-IotaGo

on:
  pull_request:
    branches: [ "develop" ]

jobs:

  TestAndBuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Test
      run: |
        cd clients/iota-go
        go test -v ./...

